name: Startup Incubation App CI

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22]


    environment: MONGO_URI

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set CI environment variable to false
      run: echo "CI=false" >> $GITHUB_ENV

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Print Env Secret
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        PORT: ${{ secrets.PORT }}
      run: | 
        echo "Secret 1 is: $MONGO_URI"
        echo "Secret 2 is: $JWT_SECRET"
        echo "Secret 3 is: $PORT"
      
    - name: Stop all PM2 processes
      run: pm2 stop all || true

    # Install dependencies for backend
    - name: Install Backend Dependencies
      working-directory: ./backend
      run: | 
       npm install --global yarn
       yarn --version
       yarn install
      
    # Install dependencies for frontend
    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: |
        df -h
        sudo rm -rf ./build
        yarn install
        yarn run build

    # Run backend tests
    - name: Run Backend Tests
      working-directory: ./backend
      run: yarn test

    - name: Create backend .env file
      working-directory: ./backend
      run: | 
        echo "${{ secrets.PROD }}" > .env

    - name: start PM2 processes
      run: pm2 start all

    - name: restart PM2 processes
      run: pm2 restart all