name: Startup Incubation App CI

on:
  push:
    branches: [main] # Trigger CI on pushes on the main branch

jobs:
  test:
    name: Run Tests
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22]

    environment: MONGO_URI

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # - name: Set CI environment variable to false
    #   run: echo "CI=false" >> $GITHUB_ENV

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Print Env Secret
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        PORT: ${{ secrets.PORT }}
      run: | 
        echo "Secret 1 is: $MONGO_URI"
        echo "Secret 2 is: $JWT_SECRET"
        echo "Secret 3 is: $PORT"
      
    - name: Stop all PM2 processes
      run: pm2 stop all || true

    # Install dependencies for backend
    - name: Install Backend Dependencies
      working-directory: ./backend
      run: | 
       npm install --global yarn
       yarn --version
       npm install
      
    # Install dependencies for frontend
    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: |
        df -h
        yarn install
        sudo rm -rf ./build
        yarn run build

    # Run backend tests
    - name: Run Backend Tests
      working-directory: ./backend
      run: yarn test

    - name: Clean install from lockfile
      run: npm ci

    - name: Create backend .env file
      working-directory: ./backend
      run: | 
        touch .env
        echo "${{ secrets.PROD }}" > .env

    - name: Show PM2 process list
      run: pm2 list || true
    
    - working-directory: ./backend
      run: |
        pm2 start "npm run start" --name="backend"
    
    - working-directory: ./frontend
      run: |
        pm2 serve build/ 3000 --name="frontend" --spa    
        
    - name: restart PM2 processes
      run: pm2 restart all